export const server = import.meta.env.VITE_SERVER || "http://localhost:3000";

export const EVENTS = {
  ALERT: "ALERT",
  REFETCH_CHATS: "REFETCH_CHATS",
  NEW_ATTACHMENT: "NEW_ATTACHMENT",
  NEW_MESSAGE_ALERT: "NEW_MESSAGE_ALERT",
  NEW_REQUEST: "NEW_REQUEST",
  NEW_MESSAGE: "NEW_MESSAGE",
  MESSAGE_DELIVERED: "MESSAGE_DELIVERED",
  MESSAGE_READ: "MESSAGE_READ",
  START_TYPING: "START_TYPING",
  STOP_TYPING: "STOP_TYPING",
  CHAT_JOINED: "CHAT_JOINED",
  CHAT_LEAVED: "CHAT_LEAVED",
  ONLINE_USERS: "ONLINE_USERS",
  CALL_OFFER: "CALL_OFFER",
  CALL_ANSWER: "CALL_ANSWER",
  ICE_CANDIDATE: "ICE_CANDIDATE",
  CALL_ENDED: "CALL_ENDED",
  STATUS_UPDATED: "STATUS_UPDATED",
} as const;
