const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const MESSAGE_DELIVERED = "MESSAGE_DELIVERED";
const MESSAGE_READ = "MESSAGE_READ";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";
const CALL_OFFER = "CALL_OFFER";
const CALL_ANSWER = "CALL_ANSWER";
const ICE_CANDIDATE = "ICE_CANDIDATE";
const CALL_ENDED = "CALL_ENDED";

const STATUS_UPDATED = "STATUS_UPDATED";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  MESSAGE_DELIVERED,
  MESSAGE_READ,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  CALL_OFFER,
  CALL_ANSWER,
  ICE_CANDIDATE,
  CALL_ENDED,
  STATUS_UPDATED,
};
